### ISSUE TITLE
Names of signs are route descriptions

### ISSUE THREAD

**Issue by cdondrup** [LAAS-HRI/semantic_route_description#7]
I noticed that the name of `gf_toilets_signpost_2` for example is `'the toilets are just right in the hall'`. Shouldn't it be `toilet sign` or similar? If I want to say something like:

```
"Take the door left of the toilet sign" 
```

to specify that I mean `door_h20`, I somehow need to get the name of it, i.e. `toilet sign`.

**Comment by sarthou** [comment]
Yes, you're right, it was for a very fast old verbalisation ... I modify it as soon as possible

**Comment by sarthou** [comment]
It is done. Tell me if the [changes](https://github.com/LAAS-HRI/semantic_route_description/commit/f374693d464f890d9c0d90bc26d399a56d1740cc) are good for you.

If you find other strange things, feel free to fork the repository and make a few pull-requests.
